name: Deploy to AWS EC2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Docker image
        run: |
          docker build -t cosmoscraper .

      - name: Save Docker image to a tarball
        run: |
          docker save cosmoscraper -o cosmoscraper.tar

      - name: Create SSH key file
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /home/runner/.ssh/ec2_key
          chmod 400 /home/runner/.ssh/ec2_key

      - name: Transfer Docker image to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          scp -o StrictHostKeyChecking=no -i /home/runner/.ssh/ec2_key cosmoscraper.tar $EC2_USER@$EC2_HOST:/home/ec2-user/
          
      - name: Deploy Docker image on EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          PORT: ${{ secrets.PORT }}
        run: |
          ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $EC2_USER@$EC2_HOST << 'EOF'
          docker load -i /home/ec2-user/cosmoscraper.tar
          docker stop app || true
          docker rm app || true
          docker run -d --name cosmoscraper -p 5000:5000 \
            -e MONGODB_URI=$MONGODB_URI \
            -e PORT=$PORT \
            cosmoscraper
          EOF
