# Global configuration
global:
  scrape_interval: 15s  # Default scrape interval for all jobs

# Scrape configuration
scrape_configs:
  - job_name: 'render_app'
    static_configs:
      - targets: ['your-render-app-url/metrics']
